using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoundWave.Identity.Common;
using SoundWave.Identity.Data.Entites;
using SoundWave.SharedKernel.Common;

namespace SoundWave.Identity.Data.Config;

internal class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users", Constants.SCHEMA_NAME);

        builder.HasKey(u => u.Id);

        // GUID v7 is assigned in application code before insert — never generated by the DB
        builder.Property(u => u.Id)
            .ValueGeneratedNever();

        builder.Property(u => u.Email)
            .IsRequired()
            .HasMaxLength(256);

        builder.HasIndex(u => u.Email)
            .IsUnique();

        builder.Property(u => u.PasswordHash)
            .IsRequired()
            .HasMaxLength(512);

        builder.Property(u => u.Role)
            .IsRequired();

        builder.Property(u => u.IsEmailVerified)
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(u => u.LockoutUntilUtc);

        builder.Property(u => u.FollowerCount)
            .IsRequired()
            .HasDefaultValue(0);

        builder.Property(u => u.FollowingCount)
            .IsRequired()
            .HasDefaultValue(0);

        builder.Property(u => u.IsDeleted)
            .IsRequired()
            .HasDefaultValue(false);

        // 1:1 — UserProfile owns the FK (configured in UserProfileConfiguration)
        builder.HasOne(u => u.UserProfile)
            .WithOne(p => p.User)
            .HasForeignKey<UserProfile>(p => p.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // 0..1 — AdminProfile only exists for Admin-role users
        builder.HasOne(u => u.AdminProfile)
            .WithOne(a => a.User)
            .HasForeignKey<AdminProfile>(a => a.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // 1:N — a user can have many refresh tokens
        builder.HasMany(u => u.RefreshTokens)
            .WithOne(rt => rt.User)
            .HasForeignKey(rt => rt.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Global soft-delete query filter
        builder.HasQueryFilter(u => !u.IsDeleted);
    }
}
