// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundWave.API.Data;

#nullable disable

namespace SoundWave.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905110951_AddCoverImageUrlToUserProfile")]
    partial class AddCoverImageUrlToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "SharedKernel");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessages", "SharedKernel");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "SharedKernel");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AlbumType")
                        .HasColumnType("tinyint");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrackCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.AlbumArtist", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("AlbumArtists", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.AlbumGenre", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AlbumGenres", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyListeners")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("TotalStreams")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Artists", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.ArtistAccountApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ArtistAccountApprovals", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackFile", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("HlsPlaylistPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PreviewPlaylistPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackId");

                    b.ToTable("TrackFiles", (string)null);
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TrackGenres", (string)null);
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.AdminProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanApproveArtists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanLockUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanViewAuditLogs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CanApproveArtists = true,
                            CanLockUsers = true,
                            CanViewAuditLogs = true,
                            CreatedDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            IsDeleted = false,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CD",
                            Name = "Congo, Democratic Republic"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CI",
                            Name = "Cote d Ivoire"
                        },
                        new
                        {
                            Id = 43,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 47,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Code = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 90,
                            Code = "KP",
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 91,
                            Code = "KR",
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 92,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 93,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 94,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 95,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 96,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 97,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 98,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 99,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 100,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 101,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 102,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 103,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 104,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 105,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 106,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 107,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 108,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 109,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 110,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 111,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 112,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 113,
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 115,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 116,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 117,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 118,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 119,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 120,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 121,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 122,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 123,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 124,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 125,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 126,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 127,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 128,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 130,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 135,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 137,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 139,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 140,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 142,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 143,
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 144,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 145,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 146,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 147,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 148,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 149,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 150,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 151,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 152,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 153,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 154,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 155,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 156,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 157,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 158,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 159,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 160,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 161,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 162,
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 163,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 164,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 165,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 166,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 167,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 168,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 169,
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 170,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 171,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 172,
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 173,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 174,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 175,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 176,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 177,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 178,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 179,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 180,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 181,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 182,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 183,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 184,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 185,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 186,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 187,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 188,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 189,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 190,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "Auth");
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FollowerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FollowingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@soundwave.com",
                            FollowerCount = 0,
                            FollowingCount = 0,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$11$IuYQ6gpIFG5UdYqEi3U88.cSBGwoiZgqQOJwA37t7U7OOgmF//J5W",
                            Role = 2
                        });
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Administrator",
                            FirstName = "System",
                            Gender = 2,
                            IsDeleted = false,
                            Language = "en",
                            LastName = "Admin",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.LikedAlbum", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedAlbums", "Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.LikedPlaylist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedPlaylists", "Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.LikedTrack", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "TrackId");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedTracks", "Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FollowerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalDurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrackCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Visibility")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Visibility");

                    b.HasIndex("OwnerId", "IsSystem");

                    b.ToTable("Playlists", "Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.PlaylistCollaborator", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlaylistId", "UserId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistCollaborators", "Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.PlaylistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PlaylistId", "Position");

                    b.HasIndex("PlaylistId", "TrackId");

                    b.ToTable("PlaylistTracks", "Playlist");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.AlbumArtist", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Album", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundWave.Catalog.Data.Entities.Artist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.AlbumGenre", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Album", "Album")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundWave.Catalog.Data.Entities.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Track", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackArtist", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Artist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundWave.Catalog.Data.Entities.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackFile", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Track", "Track")
                        .WithOne("TrackFile")
                        .HasForeignKey("SoundWave.Catalog.Data.Entities.TrackFile", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.TrackGenre", b =>
                {
                    b.HasOne("SoundWave.Catalog.Data.Entities.Genre", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundWave.Catalog.Data.Entities.Track", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.AdminProfile", b =>
                {
                    b.HasOne("SoundWave.Identity.Data.Entites.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("SoundWave.Identity.Data.Entites.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.RefreshToken", b =>
                {
                    b.HasOne("SoundWave.Identity.Data.Entites.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.UserProfile", b =>
                {
                    b.HasOne("SoundWave.Identity.Data.Entites.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoundWave.Identity.Data.Entites.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("SoundWave.Identity.Data.Entites.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.LikedPlaylist", b =>
                {
                    b.HasOne("SoundWave.Playlist.Data.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.PlaylistCollaborator", b =>
                {
                    b.HasOne("SoundWave.Playlist.Data.Entities.Playlist", "Playlist")
                        .WithMany("Collaborators")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("SoundWave.Playlist.Data.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Album", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("AlbumGenres");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Artist", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Genre", b =>
                {
                    b.Navigation("AlbumGenres");

                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("SoundWave.Catalog.Data.Entities.Track", b =>
                {
                    b.Navigation("TrackArtists");

                    b.Navigation("TrackFile");

                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("SoundWave.Identity.Data.Entites.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoundWave.Playlist.Data.Entities.Playlist", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("PlaylistTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
